### ISSUE TITLE
Proxy domain help

### ISSUE THREAD

**Issue by Gamer-20A** [SamEureka/balenaCodeServer#70]
I’ve just added my subdomain to that variable but it does not work , I guess I set it up wrong can you say me how to set it up , I am kinda new so please help

**Comment by SamEureka** [comment]
That variable only applies if you are using a reverse proxy like nginx or caddy to forward traffic to your code-server when using your own domain. You'll need to setup dns to point at your public ip and setup port forwarding on your router.  

Do you have your own domain that you would like to use? I recommend adding the [caddy-reverso](https://github.com/SamEureka/caddy-reverso) service to your docker-compose.yml file. It is a pretty easy way to do reverse proxy on a balena device. 

If you don't have a domain and can't forward traffic through your firewall to the balenaCodeServer device, you can just access your device using the ip address at port 8080. An example would be `http://192.168.0.42:8080`

What is your use-case for balenaCodeServer? How do you want to access it and what kind of device is it hosted on?

I'll help if I can.

V/R,
//Sam

**Comment by Gamer-20A** [comment]
> That variable only applies if you are using a reverse proxy like nginx or caddy to forward traffic to your code-server when using your own domain. You'll need to setup dns to point at your public ip and setup port forwarding on your router.
> 
> Do you have your own domain that you would like to use? I recommend adding the [caddy-reverso](https://github.com/SamEureka/caddy-reverso) service to your docker-compose.yml file. It is a pretty easy way to do reverse proxy on a balena device.
> 
> If you don't have a domain and can't forward traffic through your firewall to the balenaCodeServer device, you can just access your device using the ip address at port 8080. An example would be `http://192.168.0.42:8080`
> 
> What is your use-case for balenaCodeServer? How do you want to access it and what kind of device is it hosted on?
> 
> I'll help if I can.
> 
> V/R, //Sam


Use case is for my personal java projects, i want to access it from the local ip and a subdomain too and it is hosted on a raspberry pi 4(using 64bit os) i do not know how to do, the reverse proxy thing, i just added a subdomain and left it, i have some experience with nginx but it does not have a app for balena, i want assistance in this

**Comment by Gamer-20A** [comment]
I require some docker fleet for this
