### ISSUE TITLE
I Need help with proxy domain

### ISSUE THREAD

**Issue by Gamer-20A** [SamEureka/balenaCodeServer#71]
I use balena code server for running java projects on a raspberry pi 4 model b+ which is running nextcloud also , and i want thought the proxy domain will proxy that port so it can let me access code server through the subdomain

**Comment by SamEureka** [comment]
@Gamer-20A,

I think what you need is out of the scope of help that I can provide to you. I suggest researching "self-hosting from your home network", "reverse-proxy configuration", "domain nameserver and dns A record configuration". 

Likely your balena code-server device is ready to go and you just need to configure a reverse-proxy to point to it and a dns A record to point your domain to your reverse-proxy server. I know, sounds easy... but those steps are complicated and very specific to the equipment and domains you own, not to mention your internet service provider.

It can't hurt to take the time to learn how to do these networking fundamentals on your own.

Good luck!
//Sam
