### ISSUE TITLE
Nice work... and it works...

### ISSUE THREAD

**Issue by neilyoung** [SamEureka/balenaCodeServer#75]
...but out of curiosity: What is the motivation behind it? To be able to “work” on the PI with VSCode - isn't remote SSH into the respective container also sufficient? Really just out of curiosity

**Comment by SamEureka** [comment]
@neilyoung, 

Thanks! the true motivation was just to learn how balenaCloud worked. I wanted learn how balena apps/fleets worked and if I could modify the base images from vendors like [LinuxServer.io](https://www.linuxserver.io/) in a balena push/build operation. It ended up being kinda cool in the end, so I put it on the [balenaHub](https://hub.balena.io/apps) for others to play with.

At the time I didn't know about the Remote plugin for VS Code. I actually use that all the time now! 

This project might have a use case for someone, so still try to keep it sort-of up-to-date... I have one running on a generic AMD64 device behind a reverse proxy. But I rarely use it.

I have a bunch of other projects on balenaHub. Most of them are "I wonder if I can get XXX to run in a balena fleet?!" type projects.

Thanks for asking a thought provoking question! I never really thought about the motivations.

Happy coding!
//Sam

**Comment by neilyoung** [comment]
Thanks for elaborating and good luck with you projects.
